import { GET_SIGNLE_PRODUCT } from './single';
import { GET_BEST_SALLER_PRODUCTS } from './bestSeller';
import { GET_FOOTER_PRODUCTS } from './footer';
import { SEARCH_PRODUCTS } from './search';
import { GET_SHOP_PRODUCTS, GET_PAGE_PRODUCTS, GET_PRODUCTS_SLUG } from './shop';
import { GET_CATEGORY_PRODUCTS, GET_MORE_CATEGORY_PRODUCTS, GET_CATEGORIES } from './byCategory';
import { GET_COLORS, GET_COLOR_PRODUCTS, GET_MORE_COLOR_PRODUCTS } from './byColor';
import { GET_SIZES, GET_MORE_SIZE_PRODUCTS, GET_SIZE_PRODUCTS } from './bySize';
import { GET_DESIGNS, GET_DESIGNS_PRODUCTS, GET_MORE_DESIGNS_PRODUCTS } from './byDesign';

export {
  GET_SIGNLE_PRODUCT,
  GET_BEST_SALLER_PRODUCTS,
  GET_FOOTER_PRODUCTS,
  SEARCH_PRODUCTS,
  GET_SHOP_PRODUCTS,
  GET_PAGE_PRODUCTS,
  GET_CATEGORY_PRODUCTS,
  GET_MORE_CATEGORY_PRODUCTS,
  GET_CATEGORIES,
  GET_COLORS,
  GET_COLOR_PRODUCTS,
  GET_MORE_COLOR_PRODUCTS,
  GET_SIZES,
  GET_MORE_SIZE_PRODUCTS,
  GET_SIZE_PRODUCTS,
  GET_DESIGNS,
  GET_DESIGNS_PRODUCTS,
  GET_MORE_DESIGNS_PRODUCTS,
  GET_PRODUCTS_SLUG,
};
